06-ASP.NET MVC/task4-8/MyBlog/MyBlog.WebUI/Controllers/QuestionaryController.cs
using MyBlog.Domain.Entities;
using MyBlog.WebUI.Models;
using MyBlog.WebUI.Models.DbFirst;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace MyBlog.WebUI.Controllers
{
    public class QuestionaryController : Controller
    {
        //
        // GET: /Questionary/
        MyBlogRepository repository = MyBlogRepository.Instance;
        AboutSelfFormViewModel result;
        BuildRadioOrCheck checkRadioBuilder = new BuildRadioOrCheck();
        public QuestionaryController()
        {
            result = new AboutSelfFormViewModel(repository);
        }
        
        private IEnumerable<SelectListItem> GetUsers()
        {
            IEnumerable<SelectListItem> Users =
            repository.Users.Select(x => new SelectListItem()
            {
                Value = x.Id.ToString(),
                Text = x.Nick
            });
            return Users;
        }
        private void PrepareView()
        {
            result.GenderRadio = checkRadioBuilder.Build(result.GenderText, "gender", false);
            result.HobbiesChek = checkRadioBuilder.Build(result.HobbyText, "hobbies", true);
            ViewBag.List = GetUsers();
        }
        public ActionResult Index()
        {
            PrepareView();
            return View(result);
        }             [HttpPost]        public ActionResult AddAbout(AboutSelf AboutSelf, FormCollection form)
        {
            AboutSelf.Sex = form["gender"];
            AboutSelf.Hobbies = form["hobbies"];
            if (ModelState.IsValid)
            {
                ViewBag.Message = repository.AddAbout(AboutSelf);
                return View();
            }
            else
            {
                PrepareView();
                return View("Index", result);
            }
        }
    }
}

06-ASP.NET MVC/task4-8/MyBlog/MyBlog.WebUI/Views/Questionary/AddAbout.cshtml
@{
    ViewBag.Title = "Завершение анкетирования";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section single_column{
    <h2>@ViewBag.Message</h2>
    @Html.ActionLink("Назад","Index")
}

06-ASP.NET MVC/task4-8/MyBlog/MyBlog.WebUI/Views/Questionary/Index.cshtml
@model MyBlog.WebUI.Models.DbFirst.AboutSelfFormViewModel
@{
    ViewBag.Title = "Анкета";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section questionary_style{
    <link href="@Url.Content("~/Content/Styles/Questionary.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Styles/Validation.css")" rel="stylesheet" type="text/css" />
}

@section single_column{
    <div class="questionary">
    <h2>Анкета</h2>
    @using MyBlog.WebUI.Helpers
    @using (Html.BeginForm("AddAbout", "Questionary"))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="user">
            Вы: @Html.DropDownListFor(model => model.AboutSelf.UserId, ViewBag.List as IEnumerable<SelectListItem>)
        </div>
            <span>Имя: </span>
            <div class="editor-field">
                @Html.TextBoxFor(model => model.AboutSelf.Name, new { placeholder = "Введите имя" })
                @Html.ValidationMessageFor(model => model.AboutSelf.Name)
            </div>
        <span> Пол:</span>
        <div class="editor-field">
            @Html.CreateList(Model.GenderRadio, "answers", true)
        </div>
        <span> Любимые хобби:</span>
        @Html.CreateList(Model.HobbiesChek, "answers", true)
        <span>О себе:</span> <br />
        @Html.TextAreaFor(model => model.AboutSelf.About, new { placeholder = "Расскажите о себе", @class = "aboutSelf" })
        <br /><input type="submit" value="Завершить" />
    }
    </div>
}